<a href="https://colab.research.google.com/github/YungKing1224/Python-data-science/blob/main/encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LinearRegression

In [2]:
le = LabelEncoder()

In [3]:
# Use the 'raw' link to get the CSV data
url = "https://raw.githubusercontent.com/codebasics/py/master/ML/5_one_hot_encoding/Exercise/carprices.csv"

df = pd.read_csv(url)
df

Car Model  Mileage  Sell Price($)  Age(yrs)
0                  BMW X5    69000          18000         6
1                  BMW X5    35000          34000         3
2                  BMW X5    57000          26100         5
3                  BMW X5    22500          40000         2
4                  BMW X5    46000          31500         4
5                 Audi A5    59000          29400         5
6                 Audi A5    52000          32000         5
7                 Audi A5    72000          19300         6
8                 Audi A5    91000          12000         8
9   Mercedez Benz C class    67000          22000         6
10  Mercedez Benz C class    83000          20000         7
11  Mercedez Benz C class    79000          21000         7
12  Mercedez Benz C class    59000          33000         5

In [4]:
df2 = df
df2['Car Model'] = le.fit_transform(df2['Car Model'])
df2

Car Model  Mileage  Sell Price($)  Age(yrs)
0           1    69000          18000         6
1           1    35000          34000         3
2           1    57000          26100         5
3           1    22500          40000         2
4           1    46000          31500         4
5           0    59000          29400         5
6           0    52000          32000         5
7           0    72000          19300         6
8           0    91000          12000         8
9           2    67000          22000         6
10          2    83000          20000         7
11          2    79000          21000         7
12          2    59000          33000         5

In [9]:
x = df2.drop(['Sell Price($)'], axis='columns')
x

Car Model  Mileage  Age(yrs)
0           1    69000         6
1           1    35000         3
2           1    57000         5
3           1    22500         2
4           1    46000         4
5           0    59000         5
6           0    52000         5
7           0    72000         6
8           0    91000         8
9           2    67000         6
10          2    83000         7
11          2    79000         7
12          2    59000         5

In [10]:
y = df2['Sell Price($)']
y

0     18000
1     34000
2     26100
3     40000
4     31500
5     29400
6     32000
7     19300
8     12000
9     22000
10    20000
11    21000
12    33000
Name: Sell Price($), dtype: int64

In [14]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [16]:
ohe = OneHotEncoder()

# Use ColumnTransformer to specify which columns to apply the encoder to
column_transformer = ColumnTransformer(
    [('one_hot_encoder', ohe, [0])],    # [0] specifies the column index
    remainder='passthrough'             # Keep the other columns unchanged
)

# Fit and transform the data
transformed_data = column_transformer.fit_transform(x)

print(transformed_data)


[[0.00e+00 1.00e+00 0.00e+00 6.90e+04 6.00e+00]
 [0.00e+00 1.00e+00 0.00e+00 3.50e+04 3.00e+00]
 [0.00e+00 1.00e+00 0.00e+00 5.70e+04 5.00e+00]
 [0.00e+00 1.00e+00 0.00e+00 2.25e+04 2.00e+00]
 [0.00e+00 1.00e+00 0.00e+00 4.60e+04 4.00e+00]
 [1.00e+00 0.00e+00 0.00e+00 5.90e+04 5.00e+00]
 [1.00e+00 0.00e+00 0.00e+00 5.20e+04 5.00e+00]
 [1.00e+00 0.00e+00 0.00e+00 7.20e+04 6.00e+00]
 [1.00e+00 0.00e+00 0.00e+00 9.10e+04 8.00e+00]
 [0.00e+00 0.00e+00 1.00e+00 6.70e+04 6.00e+00]
 [0.00e+00 0.00e+00 1.00e+00 8.30e+04 7.00e+00]
 [0.00e+00 0.00e+00 1.00e+00 7.90e+04 7.00e+00]
 [0.00e+00 0.00e+00 1.00e+00 5.90e+04 5.00e+00]]


In [20]:
transformed_data = transformed_data[:,1:]
transformed_data

array([[1.00e+00, 0.00e+00, 6.90e+04, 6.00e+00],
       [1.00e+00, 0.00e+00, 3.50e+04, 3.00e+00],
       [1.00e+00, 0.00e+00, 5.70e+04, 5.00e+00],
       [1.00e+00, 0.00e+00, 2.25e+04, 2.00e+00],
       [1.00e+00, 0.00e+00, 4.60e+04, 4.00e+00],
       [0.00e+00, 0.00e+00, 5.90e+04, 5.00e+00],
       [0.00e+00, 0.00e+00, 5.20e+04, 5.00e+00],
       [0.00e+00, 0.00e+00, 7.20e+04, 6.00e+00],
       [0.00e+00, 0.00e+00, 9.10e+04, 8.00e+00],
       [0.00e+00, 1.00e+00, 6.70e+04, 6.00e+00],
       [0.00e+00, 1.00e+00, 8.30e+04, 7.00e+00],
       [0.00e+00, 1.00e+00, 7.90e+04, 7.00e+00],
       [0.00e+00, 1.00e+00, 5.90e+04, 5.00e+00]])

In [22]:
model = LinearRegression()

In [23]:
model.fit(transformed_data, y)

LinearRegression()

In [25]:
model.score(transformed_data, y)

0.9417050937281082

# **Price of mercedez benz that is 4 yr old with mileage 45000**

In [31]:
model.predict([[0,1,45000,4]])

array([36991.31721062])

In [32]:
model.score(transformed_data, y)

0.9417050937281082